# output.R
# read formatted data generated by processing.R and generate plots and stats results
rm(list = ls())
source("source.R")

# FST detection over year ---- 
{
  df <- read.csv("FSTrecords.csv")
  
  plot_data <- df %>%
    count(FirstDetectedYear) %>%
    complete(FirstDetectedYear = (min(df$FirstDetectedYear)-5):max(df$FirstDetectedYear), 
             fill = list(n = 0)) %>%
    mutate(CumulativeTotal = cumsum(n))
  
  ggplot(plot_data, aes(x = FirstDetectedYear, y = CumulativeTotal)) +
    geom_area(fill = "#FFF176", alpha = 0.4) +
    geom_line(color = "#E65100", size = 1) +
    geom_point(data = filter(plot_data, n > 0), color = "#E65100", size = 2) +
    scale_x_continuous(limits = c(1980, 2025), 
                       breaks = seq(1985, 2025, 10)) +
    theme_classic() +
    labs(x = "Year", y = "Number of detected counties") +
    theme(aspect.ratio = 3/4)
  
  ggsave("output/time_development_counties.pdf", 
         device = cairo_pdf, family = "Arial",
         width = 3, height = 3)
}

# plot maps ----
sep_plot <- F
{
  load("data_fmt/alabama_census.rda")
  
  # FST detection year
  {
    p_FST <- ggplot(al_map_data) +
      geom_sf(aes(fill = FirstDetectedYear), color = "white", size = 0.2) +
      scale_fill_viridis_c(option = "viridis", name = NULL, breaks = c(1985, 2005, 2025)) +
      coord_sf(datum = st_crs(4326), label_graticule = "W") +
      scale_x_continuous(breaks = NULL) +
      scale_y_continuous(labels = function(x) paste0(x, "°"), breaks = 31:35) + 
      theme_minimal() +
      labs(x = NULL, y = NULL)+
      #labs(x = "Longitude", y = "Latitude") +
      theme(
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()
      ) +
      ggtitle("First detection year")
    p_FST
    ggsave_pdf_svg(file_name = "FST_map", f_width = 4, f_height = 4)
  }
  
  # road map
  {
    # each year
    if(sep_plot){
      year_list <- names(road_sensitivity_data)
      for(i_year in 1:length(year_list)){
        al_roads <- road_sensitivity_data[[i_year]]$al_roads
        al_interstates <- al_roads %>% filter(RTTYP == "I")
        ggplot() +
          geom_sf(data = al_map_data, fill = "grey90", color = "white", size = 0.2) +
          rasterise(geom_sf(data = al_roads, aes(color = "Secondary Roads"), size = 0.3), dpi = 300) +
          geom_sf(data = al_interstates, aes(color = "Interstates"), size = 0.5) +
          scale_color_manual(
            name = "Road",
            values = c("Secondary Roads" = "#333333", "Interstates" = "#EE6677")
          ) +
          theme_void() +
          ggtitle(year_list[i_year])
        ggsave(filename = sprintf("output/road_map/road_map_%s.pdf", year_list[i_year]), 
               device = cairo_pdf, family = "Arial",
               width = 3, height = 3)
      }
    }
    
    # aggregate plot
    {
      combined_roads <- purrr::imap_dfr(road_sensitivity_data, function(val, name) {
        val$al_roads %>% mutate(year = name)
      })
      combined_interstates <- combined_roads %>% filter(RTTYP == "I")
      
      p <- ggplot() +
        geom_sf(data = al_map_data, fill = "grey90", color = "white", size = 0.2) +
        rasterise(geom_sf(data = combined_roads, aes(color = "Secondary Roads"), size = 0.3), dpi = 300) +
        geom_sf(data = combined_interstates, aes(color = "Interstates"), size = 0.5) +
        facet_wrap(~year, ncol = 5) +
        scale_color_manual(
          name = "Road", values = c("Secondary Roads" = "#333333", "Interstates" = "#EE6677")
        ) +
        theme_void() +
        theme(
          strip.text = element_text(size = 12, face = "bold"), 
          legend.position = "none"
        )
      
      p
      ggsave_pdf_svg(file_name = "road_maps_all_years", f_width = 9, f_height = 9)
    }
  }
  
  # rail
  {
    # each year
    if(sep_plot){
      year_list <- names(rail_sensitivity_data)
      for(i_year in 1:length(year_list)){
        al_rails_main <- rail_sensitivity_data[[i_year]]$al_rails_main
        ggplot() +
          geom_sf(data = al_map_data, fill = "grey90", color = "white", size = 0.2) +
          geom_sf(data = al_rails_main, color = "#4477AA", size = 0.4) +
          theme_void() +
          ggtitle(year_list[i_year])
        ggsave(filename = sprintf("output/rail_map/rail_map_%s.pdf", year_list[i_year]), 
               device = cairo_pdf, family = "Arial",
               width = 3, height = 3)
      }
    }
    
    # aggregate plot
    {
      combined_rails <- purrr::imap_dfr(rail_sensitivity_data, function(val, name) {
        val$al_rails_main %>% mutate(year = name)
      })
      
      ggplot() +
        geom_sf(data = al_map_data, fill = "grey90", color = "white", size = 0.2) +
        rasterise(geom_sf(data = combined_rails,  color = "#4477AA", size = 0.4, dpi = 300)) +
        facet_wrap(~year, ncol = 5) +
        scale_color_manual(
          name = "Road", values = c("Secondary Roads" = "#333333", "Interstates" = "#EE6677")
        ) +
        theme_void() +
        theme(
          strip.text = element_text(size = 12, face = "bold"), 
          legend.position = "none"
        )
      
      ggsave_pdf_svg(file_name = "rail_maps_all_years", f_width = 9, f_height = 9)
    }
  }
  
  # overlay
  {
    al_interstates <- road_sensitivity_data[["2024"]]$al_roads |> filter(RTTYP == "I")
    p_FST + 
      rasterise(geom_sf(data = al_interstates, color = "red", size = 0.3), dpi = 300)  +
      labs(title = "Interstates (as of 2024) overlayed")
    ggsave("output/FST_interstate.pdf", 
           device = cairo_pdf, family = "Arial",
           width = 4, height = 4)
    
    al_rails_main <- rail_sensitivity_data[["2011"]]$al_rails_main
    p_FST + 
      rasterise(geom_sf(data = al_rails_main, color = "blue", size = 0.25), dpi = 300) +
      labs(title = "Railroads (as of 2011) overlayed")
    ggsave("output/FST_railroad.pdf", , 
           device = cairo_pdf, family = "Arial",
           width = 4, height = 4)
  }
  
  # population
  {
    year_list <- al_pop |> pull(year) |> unique()
    if(sep_plot){
      for( i_year in year_list){
        ggplot() +
          geom_sf(data = al_pop |> filter(year == i_year), 
                  aes(fill = density), color = "white", size = 0.1) +
          scale_fill_viridis_c(
            option = "magma", 
            labels = scales::comma,
            name = "People per\nsq km"
          ) +
          theme_void() +
          labs(title = sprintf("Alabama Population Density %d", i_year))
        
        ggsave(sprintf("output/pop/AL_population_density_%d.pdf", i_year), 
               device = cairo_pdf, family = "Arial",
               width = 4, height = 4)
      }
    }
      
    ggplot() +
      geom_sf(data = al_pop, 
              aes(fill = density), color = "white", size = 0.1) +
      scale_fill_viridis_c(
        option = "magma", 
        labels = scales::comma,
        name = "People per\nsq km"
      ) +
      facet_wrap( ~ year, ncol = 3) +
      theme_void() +
      labs(title = sprintf("Alabama Population Density"))+
      theme(legend.position = "bottom")
    
    ggsave_pdf_svg(file_name = "AL_population_density", f_width = 8, f_height = 4)
  }
}

# time development of census data ----
{
  df_termite <- read.csv("FSTrecords.csv")
  load("data_fmt/alabama_census.rda")
  load("data_fmt/df_alabama_climate.rda")
  
  plot_style <- list(
    theme_bw(base_size = 9),
    guides(color = guide_legend(
      direction = "horizontal", 
      title.position = "left",
      title.vjust = 0.5   
    )), 
    theme(panel.grid = element_blank(),
          aspect.ratio = 3/4,
          strip.background = element_blank(),
          strip.text = element_text(face = "bold", size = 7), 
          axis.text.x = element_text(angle = 45, hjust = 1, size = 6), 
          axis.text.y = element_text(size = 6),
          legend.position = c(0.85, 0.03),
          legend.background = element_blank(), 
          legend.text = element_text(size = 7),
          legend.title = element_blank())
  )
  
  prep_plot_data <- function(df, target_var){
    df %>% 
      left_join(df_termite, by = join_by(NAME == "County")) %>%
      mutate(
        cens = !is.na(FirstDetectedYear),
        across(FirstDetectedYear, ~ replace_na(.x, 2025)),
        year_till_detect = FirstDetectedYear - 1984,
        cens = factor(cens, levels = c("TRUE", "FALSE"), labels = c("Detected", "Not Detected")),
        NAME = fct_reorder(NAME, .data[[target_var]], .fun = max, .desc = TRUE)
      )
  }
  
  pw = 7.8
  ph = 6
  
  # population
  df_pop_plot <- prep_plot_data(al_pop |> st_drop_geometry(), "density")
  
  ggplot(df_pop_plot, aes(x = year, y = density)) +
    geom_line(aes(col = cens), linewidth = 0.7) +
    scale_y_continuous(limits = c(0, 300), breaks = c(0,100,200,300)) +
    scale_color_manual(name = "", values = c("Detected" = "#FF5555", "Not Detected" = "#555555")) +
    facet_wrap(~ NAME, ncol = 10) +
    labs(x = "", y = "Population density (/km2)") +
    plot_style +
    geom_vline(data = df_pop_plot |> filter(cens == "Detected"), 
               aes(xintercept = FirstDetectedYear), linetype = "dashed", color = "darkgray")
  
  ggsave(filename = "output/Population_density_over_year.svg", 
         device = svglite, fix_text_size = FALSE, 
         width = pw, height = ph, bg = "transparent")
  
  spearman_matrix <- df_pop_plot %>%
    select(NAME, year, density) %>%
    pivot_wider(names_from = year, values_from = density) %>%
    select(-NAME) %>%
    cor(method = "spearman", use = "pairwise.complete.obs")
  
  print(spearman_matrix |> round(3)) 
  min(spearman_matrix)
  
  # traffic
  df_traffic_plot <- prep_plot_data(df_traffic, "road_density_woIS")
  
  ggplot(df_traffic_plot, aes(x = year)) +
    geom_line(aes(y = road_density_woIS, col = cens), linewidth = 0.7) +
    scale_color_manual(name = "", values = c("Detected" = "#FF5555", "Not Detected" = "#555555")) +
    scale_x_continuous(limits = c(2010, 2025)) +
    scale_y_continuous(limits = c(-0.05, 1.05), breaks = c(0,0.5,1), labels = c(0,0.5,1)) +
    plot_style +
    new_scale_color() + 
    geom_line(aes(y = rail_density, col = cens), linewidth = 0.7, linetype = 4) +
    scale_color_manual(name = "", values = c("Detected" = "#5555FF", "Not Detected" = "#555555")) +
    new_scale_color() + 
    geom_path(aes(y = IS_presence * 1, col = cens), linewidth = 0.7) +
    scale_color_manual(name = "", values = c("Detected" = viridis(4)[3], "Not Detected" = "#555555")) +
    facet_wrap(~ NAME, ncol = 10) +
    labs(x = "", y = "Road / Rail density (km / km2) / IS presence") +
    geom_vline(data = df_traffic_plot |> filter(cens == "Detected"), 
               aes(xintercept = FirstDetectedYear), linetype = "dashed", color = "darkgray")
  
  ggsave(filename = "output/Traffic_over_year.svg", 
         device = svglite, fix_text_size = FALSE, 
         width = pw, height = ph, bg = "transparent")
  
  # Climate
  df_alabama_climate_plot <- prep_plot_data(df_alabama_climate, "temp_mean_C")
  
  ggplot(df_alabama_climate_plot, aes(x = year)) +
    geom_path(aes(y = temp_mean_C * 1, col = cens), linewidth = 0.7) +
    scale_color_manual(name = "", values = c("Detected" = "#FF5555", "Not Detected" = "#555555")) +
    new_scale_color() + 
    geom_line(aes(y = temp_min_C, col = cens), linewidth = 0.7) +
    scale_color_manual(name = "", values = c("Detected" = "#5555FF", "Not Detected" = "#555555")) +
    facet_wrap(~ NAME, ncol = 10) +
    labs(x = "", y = "Temperature (°C)") +
    plot_style+
    geom_vline(data = df_alabama_climate_plot |> filter(cens == "Detected"), 
               aes(xintercept = FirstDetectedYear), linetype = "dashed", color = "darkgray")
  
  ggsave(filename = "output/Temperature_over_year.svg", 
         device = svglite, fix_text_size = FALSE, 
         width = pw, height = ph, bg = "transparent")
}

# correlation ----
{
  load("data_fmt/df_surv.rda")
  
  plot_correlation <- function(var_mapping, df_surv){
    plot_order <- unname(var_mapping)
    
    df_mat <- df_surv |>
      dplyr::select(any_of(names(var_mapping))) |>
      mutate(
        across(where(is.logical), as.numeric),
        across(where(is.factor), ~ as.numeric(.x) - 1)
      )
    
    cor_mat <- cor(df_mat, method = "spearman", use = "complete.obs")
    
    cor_df <- as.data.frame(cor_mat) |>
      tibble::rownames_to_column("Var1") |>
      pivot_longer(-Var1, names_to = "Var2", values_to = "correlation") |>
      filter(!is.na(correlation)) |>
      mutate(
        Var1 = var_mapping[Var1],
        Var2 = var_mapping[Var2],
        Var1 = factor(Var1, levels = plot_order),
        Var2 = factor(Var2, levels = plot_order)
      )
    
    p_cor <- ggplot(cor_df, aes(x = Var2, y = Var1, fill = correlation)) +
      geom_tile(color = "white") +
      geom_text(aes(label = ifelse(abs(correlation) > 0.6 & correlation < 1, sprintf("%.2f", correlation), "")),
        color = "black", size = 2) +
      scale_fill_distiller(palette = "RdBu", limit = c(-1, 1), direction = 1, 
                           name = "Spearman\nCorrelation") +
      theme_minimal(base_size = 8) +
      theme(
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, color = "black"),
        axis.text.y = element_text(color = "black"),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        aspect.ratio = 1
      )
    
    p_cor
  }
  
  # main
  var_mapping <- c(
    "mean_temp_mean"         = "Mean Temp (1984-2025)",
    "mean_temp_min"          = "Min Temp (1984-2025)",
    "lat"                    = "Latitude",
    "IS_presence_2011"       = "IS Presence 2011",
    "IS_presence_2025"       = "IS Presence 2025",
    "popdens_1980"           = "Pop Density 1980",
    "popdens_2024"           = "Pop Density 2025",
    "rail_density_2011"      = "Rail Density 2011",
    "rail_density_2025"      = "Rail Density 2025",
    "road_density_wIS_2011"  = "Road Dens w/ IS 2011",
    "road_density_wIS_2025"  = "Road Dens w/ IS 2025",
    "road_density_woIS_2011" = "Road Dens w/o IS 2011",
    "road_density_woIS_2025" = "Road Dens w/o IS 2025",
    "year_till_detect"       = "Years to Detection"
  )
  plot_correlation(var_mapping, df_surv)
  ggsave_pdf_svg(file_name = "variable_correlation_main", f_width = 5.7, f_height = 5.7)
  
  # 2000
  var_mapping <- c(
    "lat"                    = "Latitude",
    "Highway_presence_2000"  = "Highway presence 2000",
    "IS_presence_2011"       = "IS Presence 2011",
    "IS_presence_2025"       = "IS Presence 2025",
    "popdens_2024"           = "Pop Density 2024",
    "rail_density_2000"      = "Rail Number Density 2000",
    "rail_density_2011"      = "Rail Density 2011",
    "rail_density_2025"      = "Rail Density 2025",
    "road_density_2000"      = "Road Number Density 2000",
    "road_density_woIS_2011" = "Road Dens 2011",
    "road_density_woIS_2025" = "Road Dens 2025",
    "year_till_detect"       = "Years to Detection"
  )
  plot_correlation(var_mapping, df_surv)
  ggsave_pdf_svg(file_name = "variable_correlation_2000", f_width = 4, f_height = 4)
}

# survival analysis ----
# note
# coxph model: h_i(t) = h_0(t)e^(η_i); η_i = x_iβ
# η_i: linear predictor, called as Cox risk score or log-relative hazard score
# e^(η_i): exponential linear predictor, called as relative hazard score
# h_0(t)e^(η_i): hazard
# h_i(t) / h_reference(t): hazard ratio
{
  load("data_fmt/df_surv.rda")
  
  traffic_years <- 2011:2025
  pop_years <- c(1980,1990,2000,2010,2020)
  
  make_traffic_formula <- function(year = 2011, road_variable = "road_density_woIS",
                                   climate_variable = "lat", pop_year = 2024) {
    reformulate(
      c(paste0("rail_density_", year),
        paste0("IS_presence_", year), 
        paste0(road_variable, "_", year),
        climate_variable, 
        paste0("popdens_", pop_year)
        ),
      response = "Surv(year_till_detect, cens)"
    )
  }

  # models ----
  {
    year_models <- traffic_years |>
      setNames(paste0("traffic_", traffic_years)) |>
      purrr::map(\(year) {
        coxph(make_traffic_formula(year = year), data = df_surv)
      })
    
    pop_model <- pop_years |>
      setNames(paste0("pop_", pop_years)) |>
      purrr::map(\(pop_years) {
        coxph(make_traffic_formula(pop_year = pop_years), data = df_surv)
      })
    
    other_models <- list(
      road_wIS_2011 = coxph(make_traffic_formula(year = 2011, road_variable = "road_density_wIS"),
        data = df_surv),
      
      road_wIS_2025 = coxph(make_traffic_formula(year = 2025, road_variable = "road_density_wIS"),
        data = df_surv),
      
      temp_mean = coxph(make_traffic_formula(year = 2011, climate_variable = "mean_temp_mean"),
        data = df_surv),
      
      temp_min = coxph(make_traffic_formula(year = 2011, climate_variable = "mean_temp_min"),
        data = df_surv),
      
      remove_road = 
        coxph(Surv(year_till_detect, cens) ~ rail_density_2011 + IS_presence_2011 + lat + popdens_2024,
        data = df_surv),
      
      remove_popdens = 
        coxph(Surv(year_till_detect, cens) ~ rail_density_2011 + IS_presence_2011 + road_density_woIS_2011 + lat,
        data = df_surv),
      
      traffic_2000 = 
        coxph(Surv(year_till_detect, cens) ~ rail_density_2000 + Highway_presence_2000 + road_density_2000 + lat + popdens_2024,
        data = df_surv
      )
    )
    
    models_all <- c(year_models, pop_model, other_models)
    
    cox_results <- purrr::imap_dfr(models_all, \(x, y) broom::tidy(x, conf.int = TRUE, exponentiate = TRUE) |> mutate(name = y))
  }
  
  # visualization ----
  {
    classify_covariate <- function(df) {
      df |> mutate(
        type = case_when(
          grepl("IS_presence_|Highway_presence_", term) ~ "Interstate presence",
          term %in% c("lat", "mean_temp_mean", "mean_temp_min") ~ "Climate",
          grepl("^popdens_", term) ~ "Population density",
          grepl("^road_density_", term) ~ "Road density\n(wo interstate)",
          grepl("^rail_density_", term) ~ "Rail density"),
        type = factor(type, levels = c("Interstate presence", "Road density\n(wo interstate)",
                                       "Rail density", "Population density",
                                       "Climate")))
    }
    
    # yearly plot
    {
      df_yearplot <- cox_results |> filter(str_detect(name, "traffic_"), name != "traffic_2000") |> 
        classify_covariate() |> mutate(
          year = as.numeric(str_split_i(name, "_", 2)),
          year_group = factor(year),
          type = as.character(type),
          type = ifelse(type == "Climate", "Latitude", type),
          type = ifelse(type == "Population density", "Population density\n(2024)", type),
          type = factor(type, levels = c("Interstate presence", "Road density\n(wo interstate)",
                                         "Rail density", "Population density\n(2024)",
                                         "Latitude")))
      
      ggplot(df_yearplot, aes(x = estimate, y = type, color = year, group = year_group)) +
        geom_vline(xintercept = 1, linetype = "dashed", color = "gray60") +
        geom_point(position = position_dodge(width = 0.5), size = 1) +
        geom_errorbarh(aes(xmin = conf.low, xmax = conf.high),
                       position = position_dodge(width = 0.5), height = 0.45, linewidth = 0.2) +
        scale_x_log10()+
        scale_color_viridis(breaks = c(2011, 2025), limits = c(2011, 2025),
                            name = "Traffic year", 
                            guide = guide_colorbar( barheight = unit(15, "mm"),
                                                    barwidth = unit(3, "mm")))+
        labs(x = "Hazard ratio", y = NULL, color = "Models") +
        theme_classic(base_size = 9) +
        theme(
          aspect.ratio = 1,
          panel.grid = element_blank(),
          strip.background = element_blank(),
          strip.text = element_text(face = "bold"),
          legend.background = element_blank(),
          legend.position = c(0.85, 0.85),
          strip.placement = "outside"
        )
      
      ggsave_pdf_svg(file_name = "cox_traffic_years", f_height = 4, f_width = 4)
    }
    
    # sensitivity analysis
    {
      df_plot_SA <- cox_results |>  filter(str_split_i(name, "_", 1) != "traffic")|>
        classify_covariate() |> mutate(
          model_type = case_when(
            grepl("pop_", name)      ~ "Population year",
            grepl("temp_", name)     ~ "Temperature data",
            grepl("road_wIS_", name) ~ "Road Interstate Inclusion",
            grepl("remove_", name)   ~ "Removal analysis"
          ),
          model_type = factor(model_type, levels = c("Population year", "Temperature data","Road Interstate Inclusion", "Removal analysis")))  |>
        rbind(cox_results |>  filter(name == "traffic_2011") |> classify_covariate() |> mutate(model_type = "Population year")) |>
        rbind(cox_results |>  filter(name == "traffic_2011") |> classify_covariate() |> mutate(model_type = "Temperature data")) |>
        rbind(cox_results |>  filter(name == "traffic_2011") |> classify_covariate() |> mutate(model_type = "Road Interstate Inclusion")) |>
        rbind(cox_results |>  filter(name == "traffic_2011") |> classify_covariate() |> mutate(model_type = "Removal analysis"))
      
      model_colors <- c(
        pop_1980 = "#c6dbef",
        pop_1990 = "#9ecae1",
        pop_2000 = "#6baed6",
        pop_2010 = "#4292c6",
        pop_2020 = "#2171b5",
        pop_2024 = "#084594",
        road_wIS_2011 = "#7570b3",
        road_wIS_2025 = "#bcbddc",
        temp_mean = "#d95f02",
        temp_min = "#fdae61",
        remove_road = "#2ca25f",
        remove_popdens = "#99d8c9",
        traffic_2011 = "#333333"
      )
      
      model_labels <- c(
        pop_1980 = "1980",
        pop_1990 = "1990",
        pop_2000 = "2000",
        pop_2010 = "2010",
        pop_2020 = "2020",
        pop_2024 = "2024",
        road_wIS_2011 = "2011",
        road_wIS_2025 = "2025",
        temp_mean = "Mean temperature",
        temp_min = "Minimum temperature",
        remove_road = "Exclude road density",
        remove_popdens = "Exclude population density",
        traffic_2011 = "Reference (2011)"
      )
      
      ggplot(df_plot_SA, aes(x = estimate, y = type, color = name)) +
        geom_vline(xintercept = 1, linetype = "dashed", color = "gray60") +
        geom_point(position = position_dodge(width = 0.5), size = 1) +
        geom_errorbarh(
          aes(xmin = conf.low, xmax = conf.high),
          position = position_dodge(width = 0.5),
          height = 0.2,
          linewidth = 0.2
        ) +
        scale_x_log10() +
        scale_color_manual(
          values = model_colors,
          breaks = names(model_labels),
          labels = model_labels
        ) +
        facet_wrap(~model_type, axes = "all", axis.labels = "all_x") +
        labs(x = "Hazard ratio (log scale)", y = NULL, color = NULL) +
        theme_classic(base_size = 9) +
        theme(
          aspect.ratio = 4/3,
          panel.grid = element_blank(),
          strip.background = element_blank(),
          strip.text = element_text(face = "bold"),
          legend.background = element_blank(),
          legend.position = "bottom",
          strip.placement = "outside"
        )
      
      ggsave_pdf_svg(file_name = "cox_comparisons", f_width = 4, f_height = 6)
    }
    
    # 2000 data
    {
      df_2000 <- cox_results |>  filter(name == "traffic_2000")|>
        rbind(cox_results |>  filter(name == "traffic_2011")) |>
        classify_covariate()
      
      model_colors <- c(
        traffic_2011 = "#333333",
        traffic_2000 = "red4"
      )
      
      model_labels <- c(
        traffic_2011 = "Reference (2011)",
        traffic_2000 = "Traffic (2000)"
      )
      
      ggplot(df_2000, aes(x = estimate, y = type, color = name)) +
        geom_vline(xintercept = 1, linetype = "dashed", color = "gray60") +
        geom_point(position = position_dodge(width = 0.5), size = 1) +
        geom_errorbarh(
          aes(xmin = conf.low, xmax = conf.high),
          position = position_dodge(width = 0.5),
          height = 0.2,
          linewidth = 0.2
        ) +
        scale_x_log10() +
        scale_color_manual(
          values = model_colors,
          breaks = names(model_labels),
          labels = model_labels
        ) +
        labs(x = "Hazard ratio (log scale)", y = NULL, color = NULL) +
        theme_classic(base_size = 9) +
        theme(
          aspect.ratio = 4/3,
          panel.grid = element_blank(),
          strip.background = element_blank(),
          strip.text = element_text(face = "bold"),
          legend.background = element_blank(),
          legend.position = "bottom",
          strip.placement = "outside"
        )
      
      ggsave_pdf_svg(file_name = "cox_2000", f_width = 4, f_height = 6)
    }
  }
    
  # model tables
  {
    term_labels <- c(
      setNames(paste0("Rail density (", traffic_years, ")"), paste0("rail_density_", traffic_years)),
      setNames(paste0("Interstate present (", traffic_years, ")"), paste0("IS_presence_", traffic_years, "TRUE")),
      setNames(paste0("Road density incl. interstate (", traffic_years, ")"), paste0("road_density_wIS_", traffic_years)),
      setNames(paste0("Road density excl. interstate (", traffic_years, ")"), paste0("road_density_woIS_", traffic_years)),
      rail_density_2000 = "Rail feature density (2000)",
      road_density_2000 = "Road feature density (2000)",
      Highway_presence_2000TRUE = "Highway present (2000)",
      setNames(paste0("Population density (", pop_years, ")"), paste0("popdens_", pop_years)),
      lat = "Latitude",
      mean_temp_mean = "Mean annual temperature",
      mean_temp_min = "Minimum temperature"
    )
    
    format_cox_table <- function(model_list) {
      purrr::imap_dfr(model_list, \(mod, mod_name) {
        broom::tidy(mod, conf.int = TRUE, exponentiate = TRUE) |>
          mutate(
            model = dplyr::recode(mod_name, !!!model_labels),
            term = dplyr::recode(term, !!!term_labels)
          ) |>
          transmute(
            model, term, HR = estimate,
            CI_low = conf.low, CI_high = conf.high, p = p.value)
      }) |>
        mutate(
          HR_CI = sprintf("%.2f (%.2f-%.2f)", HR, CI_low, CI_high ),
          p = ifelse(p < 0.001, "<0.001", sprintf("%.3f", p))) |>
        dplyr::select(model, term, HR_CI, p)
    }
    
    create_tables <- function(model_list, table_name){
      supp_table <- format_cox_table(model_list)
      supp_table <- supp_table |> arrange(term)
      
      write.csv(supp_table, 
                file = sprintf("output/%s_stat.csv", table_name),
                row.names = FALSE)
      
      model_stats <- purrr::imap_dfr(model_list, \(mod, mod_name) {
        tibble(model = mod_name, AIC = AIC(mod), logLik = as.numeric(logLik(mod)))
      } ) |>
        mutate(delta_AIC = AIC - min(AIC)) |>
        arrange(AIC)
      
      write.csv(model_stats, 
                file = sprintf("output/%s_AIC.csv", table_name),
                row.names = FALSE)
      
      ph_table <- purrr::imap_dfr(model_list, \(mod, mod_name) {
        as.data.frame(cox.zph(mod)$table) |>
          tibble::rownames_to_column("term") |>
          transmute(
            model = mod_name,
            term,
            chisq = round(chisq, 3),
            df,
            p = round(p, 3),
          )})
      
      write.csv(ph_table, 
                file = sprintf("output/%s_phtable.csv", table_name),
                row.names = FALSE)
    }
    
    create_tables(models_all, "models_all")
    create_tables(year_models, "models_year")
    create_tables(list(models_all$traffic_2000), "models_2000")
  }
  
  # county influence analysis ----
  {
    cox_mod <- year_models$traffic_2011
    reference_formula_2011 <- make_traffic_formula(2011)
    
    reference_interstate <- broom::tidy(
      cox_mod, conf.int = TRUE, exponentiate = TRUE) |>
      filter(term == "IS_presence_2011TRUE")
    
    loo_counties <- df_surv |> filter(county != "Mobile") |>
      pull(county) |> sort()
    
    loo_results <- purrr::map_dfr(loo_counties, \(county_removed) {
      loo_mod <- coxph(reference_formula_2011, data = df_surv |> 
                         filter(county != county_removed))
        broom::tidy(loo_mod, conf.int = TRUE, exponentiate = TRUE) |>
          filter(term == "IS_presence_2011TRUE") |>
          transmute(county_removed, HR = estimate, 
                    CI_low = conf.low, CI_high = conf.high, p = p.value)
      }
    )
    
    write.csv(loo_results, file = "output/cox_leave_one_county_out.csv",
      row.names = FALSE)
    
    loo_results_plot <- loo_results |>
      arrange(HR) |>
      mutate(
        county_removed = factor(county_removed, levels = county_removed)
      )
    
    ggplot(loo_results_plot, aes(x = HR, y = county_removed)) +
      geom_vline(xintercept = 1, linetype = "dashed", color = "gray60") +
      geom_point(size = 1.5) +
      geom_errorbarh(aes(xmin = CI_low, xmax = CI_high), 
                     height = 0.15, linewidth = 0.4) +
      scale_x_log10(limits = c(0.1, 10)) +
      labs(x = "Interstate hazard ratio", y = "County removed") +
      theme_classic(base_size = 8) +
      theme(
        panel.grid = element_blank(),
        aspect.ratio = 4/3
      )
    
    ggsave_pdf_svg(file_name = "cox_leave_one_county_out",
                   f_width = 5, f_height = 6)
    
  }
  
  # reference model prediction ----
  {
    newdata <- df_surv |>
      dplyr::select(county, rail_density_2011, IS_presence_2011, road_density_woIS_2011, lat, popdens_2024) |>
      arrange(county)
    
    risk_prediction <- newdata |>
      transmute(
        county,
        risk_score = predict(cox_mod, newdata = newdata, type = "lp"), # linear predictor
        relative_hazard  = exp(risk_score)
      )
    
    risk_map <- al_map_data |> left_join(risk_prediction,by = c("NAME" = "county")) |>
      mutate(
        undetected = is.na(FirstDetectedYear),
        relative_hazard_undetected = if_else(undetected, relative_hazard, NA_real_)
      )
    
    surveillance_priority <- risk_map |> st_drop_geometry() |> filter(is.na(FirstDetectedYear)) |>
      arrange(desc(relative_hazard))|>
      dplyr::select(county = NAME, risk_score, relative_hazard) |>
      slice_head(n = 10)
    
    write.csv(surveillance_priority, file = "output/AL_FST_surveillance_priority.csv", row.names = FALSE)
    
   ggplot(risk_map) +
      geom_sf(aes(fill = relative_hazard_undetected), color = "white", size = 0.2) +
      scale_fill_viridis_c(name = "Relative\ndetection hazard", option = "inferno",
                           direction = -1, trans = "log10") +
      theme_void()
    
   ggsave_pdf_svg(file_name = "AL_FST_risk", f_width = 4, f_height = 4)
   
  }
  
  # spatial auto-correlation
  {
    cox_mod <- year_models$traffic_2011
    county_res <- residuals(cox_mod, collapse = df_surv$county)
    
    al_counties <- counties(state = "AL", cb = TRUE, year = 2025)
    al_counties <- st_transform(al_counties, 3857)
    al_counties <- al_counties |> dplyr::select(NAME)
    
    county_sf_res <- al_counties |>
      arrange(match(NAME, names(county_res))) |>
      mutate(martingale = unname(county_res[NAME]))
    
    # poly2nb() examines the county polygons (not distance) and creates a neighbor list
    nb <- poly2nb(county_sf_res, row.names = county_sf_res$NAME, queen = TRUE)
    # plot(st_geometry(county_sf_res))
    # plot(nb, st_coordinates(st_centroid(county_sf_res)), add = TRUE)
    
    lw <- nb2listw(nb, style = "W", zero.policy = TRUE)
    
    set.seed(20260728)
    res <- moran.mc(county_sf_res$martingale, lw, nsim = 9999, 
             alternative = "two.sided", zero.policy = TRUE)
    res
  }
}
